name: Deploy to AWS Lambda

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.x

    # Runs a set of commands using the runners shell
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade --target ${{ GITHUB.WORKSPACE }}/function -r requirements.txt

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        path: ${{ GITHUB.WORKSPACE }}/function

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Download Build Artifact
      uses: actions/download-artifact@v2.0.5
      with:
        name: artifact
        path: ./build
    
    - name: Zip and Deploy
      run: |
        cd ./build
        zip -r build.zip *
        aws lambda update-function-code --function-name processComments --zip-file fileb://./build.zip

